### ISSUE TITLE
add battery info

### ISSUE THREAD

**Issue by RJ1002** [Outpox/Bluetooth#7]
would it be possible to add battery info(like a % of how much charge)
and maybe when the battery get low it send a notification

also, kind of unrelated but my earbud battery percentage don't show up but my keyboard and mouse show up. but mouse battery info is not right. are you able to fix these issue? if not it fine.

**Comment by Outpox** [comment]
That's a good idea, I'll see if I can get the data first.  
  
The issue you mention is not resolvable via the plugin nor the tool it uses under the hood I'm afraid.

**Comment by Outpox** [comment]
I've looked into this feature and it's too complicated to be included in this plugin.  
The headset I've tested this on returns battery percentage to my android phone so I know that it is available.  
- `bluetoothctl info` doesn't include the battery percentage
- neither it is in `list-attributes` of the `gatt` submenu 
- Using `bluetoothctl` in its experimental version doesn't work either and breaks other features that I'm using
- `upower -d` doesn't return my headset (nor with `bluetoothctl` in experimental)
- [this library](https://github.com/TheWeirdDev/Bluetooth_Headset_Battery_Level) is promising but it's already hard to get the dependencies manually and it'd be a nightmare to do it via the plugin  
  
Let's hope Valve include it at some point so that I can reuse it.
